### DOCUMENTASI
@host = https://prestoqr.probussystem.com
https://prestoqrcode.docs.apiary.io/#

# /#/login?meja=1&host=https%3A%2F%2Fprestoqr.probussystem.com&token=CBFCC61


### lihat group
GET https://prestoqr.probussystem.com/api/getGroup?group=&subgroup= HTTP/1.1

### lihat menu
GET http://prestoqr.probussystem.net/presto/public/api/getMenu?product=&group=&subgroup= HTTP/1.1

### compeny profile
GET http://192.168.192.110/PRESTO/public/api/getCompanyProfile HTTP/1.1

### lihat data shift
# gak jadi
GET https://prestoqr.probussystem.net/presto/public/api/getShift HTTP/1.1



### set customer id
# table sesuai nomer meja
# http://192.168.192.188:8887/index.html/#/login?meja=3&host=http://192.168.192.110
# POST https://prestoqr.probussystem.com/api/setUserTable/8 HTTP/1,1
POST https://prestoqr.probussystem.com/api/setUserTable/1
Content-Type: application/json

{
    "name": "adi",
    "phone": "0987654321",
    "email": "adi@adi.com",
    "token": "zwrty"
}

# {
#     "name": "adi",
#     "phone": "0987654321",
#     "email": "adi@adi.com"
# }

# responsenya
# {
#   "status": true,
#   "user": {
#     "name": "Fitri",
#     "email": "fitridwi62@gmail.com",
#     "phone": "1111111111",
#     "created_at": "2020-09-24 12:55:14",
#     "updated_at": "2020-09-24 12:55:14",
#     "ip_address": "118.99.110.185",
#     "device_name": "vscode-restclient"
#   },
#   "table": "2",
#   "note": "Table successfully used",
#   "order": null
# }

### save customer order
# table sesuai meja
POST https://prestoqr.probussystem.com/api/saveOrder/8 HTTP/1.1
Content-Type: application/json

{
  "customer_id": "8",
  "name": "malik",
  "phone": "081338929722",
  "email": "malik@gmail.com",
  "billDetail": [
    {
      "product_id": "MSC.0002",
      "product_price": "20000",
      "qty": 2,
      "note": "extra gula"
    },
    {
      "product_id": "RST.0006",
      "product_price": "20000",
      "qty": "3",
      "note": "dijadikan 1"
    }
  ]
}

### get data order temporary
GET https://prestoqr.probussystem.com/api/listOrderTemporary HTTP/1.1

### approve temporary order
POST https://prestoqr.probussystem.com/api/aproveOrderTemporary/orderTemporary
Content-Type: application/json

{
  "pax": "2",
  "waiter_id": "1",
  "shift": "1. MORNING",
  "note": " order cepat"
}


### lihat meja
GET https://prestoqr.probussystem.com/api/getCustomerTable HTTP/1.1

### bersihkan meja
POST {{host}}/api/clearTable/1 HTTP/1.1


### setting
GET https://malikkurosaki.github.io/cdnjs/setting/presto_qr.json HTTP/1.1


###
# format
# "/login/:meja/:host"
# http://localhost:58264/#login/3/host.com


# POST https://prestoqr.probussystem.com/api/clearTable/3 HTTP/1.1
